apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-build
spec:
  workspaces:
    - name: shared
  params:
    - name: IMAGE_NAME
      type: string
      default: simple-nodejs-mvc
    - name: GIT_REPO
      type: string
      default: https://github.com/t0m0h1de/simple-nodejs-mvc
    - name: GIT_REVISION
      type: string
      default: main
    - name: CONTAINER_IMAGE_URL
      type: string
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
      workspaces:
        - name: output
          workspace: shared
    - name: build-image
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.CONTAINER_IMAGE_URL)
        - name: DOCKERFILE
          value: ./docker/nodejs/Dockerfile
        - name: SKIP_PUSH
          value: "false"
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared
