version: '3'
services:
  redis-stack:
    build:
      context: .
      dockerfile: ./docker/redis/Containerfile
    container_name: redis
    environment:
      TZ: Asia/Tokyo
    ports:
      - 6379:6379
      - 8081:8001

  redis-inserter:
    build:
      context: .
      dockerfile: ./docker/redis-inserter/Containerfile
    container_name: redis-inserter
    environment:
      TZ: Asia/Tokyo

networks:
    redisearch-gettingstarted:
        driver: bridge