apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ .Values.simpleNodejsMVC.name }}
  name: nodejs-22
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: {{ .Values.nodejs.baseImage }}
    from:
      kind: DockerImage
      name: {{ .Values.nodejs.baseImage }}
    generation: null
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""