apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.simpleNodejsMVC.name }}
  name: {{ .Values.simpleNodejsMVC.name }}
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    deployment: {{ .Values.simpleNodejsMVC.name }}
status:
  loadBalancer: {}