apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple-nodejs-mvc
      app.kubernetes.io/component: simple-nodejs-mvc
      app.kubernetes.io/instance: simple-nodejs-mvc
    name: nodejs-22
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/ubi9/nodejs-22:latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/nodejs-22:latest
      generation: null
      importPolicy:
        importMode: Legacy
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple-nodejs-mvc
      app.kubernetes.io/component: simple-nodejs-mvc
      app.kubernetes.io/instance: simple-nodejs-mvc
    name: simple-nodejs-mvc
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple-nodejs-mvc
      app.kubernetes.io/component: simple-nodejs-mvc
      app.kubernetes.io/instance: simple-nodejs-mvc
    name: simple-nodejs-mvc
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: simple-nodejs-mvc:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/t0m0h1de/simple-nodejs-mvc
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: docker/nodejs/Dockerfile
      type: Docker
    triggers:
    - github:
        secret: IiAzS8VAvaBIzqRhSrQj
      type: GitHub
    - generic:
        secret: xYt0bpLvj57WctIvJodk
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"simple-nodejs-mvc:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"simple-nodejs-mvc\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple-nodejs-mvc
      app.kubernetes.io/component: simple-nodejs-mvc
      app.kubernetes.io/instance: simple-nodejs-mvc
    name: simple-nodejs-mvc
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: simple-nodejs-mvc
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: simple-nodejs-mvc
      spec:
        containers:
        - image: ' '
          name: simple-nodejs-mvc
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: simple-nodejs-mvc
      app.kubernetes.io/component: simple-nodejs-mvc
      app.kubernetes.io/instance: simple-nodejs-mvc
    name: simple-nodejs-mvc
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deployment: simple-nodejs-mvc
  status:
    loadBalancer: {}
kind: List
metadata: {}
