apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-mvc
spec:
  template:
    spec:
      containers:
        - name: simple-nodejs-mvc
          resources:
            limits:
              memory: "512Mi"
              cpu: "600m"
